{% set version = "2.5.4" %}

package:
  name: openjpeg
  version: {{ version }}

source:
  url: https://github.com/uclouvain/openjpeg/archive/v{{ version }}.tar.gz
  sha256: a695fbe19c0165f295a8531b1e4e855cd94d0875d2f88ec4b61080677e27188a

build:
  number: 0
  run_exports:
    # good compatibility in 2.x series, check before new release
    # http://www.openjpeg.org/abi-check/timeline/openjpeg/
    - {{ pin_subpackage('openjpeg') }}
  ignore_run_exports:
    # Needed as a transitive build-time dependency to enable PNG support but
    # is not actually required by the output binaries.
    - zlib

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make   # [unix]
    - ninja  # [win]
  host:
    - libtiff
    - libpng
    - zlib

test:
  files:
    - p0_01.j2k
  commands:
    - opj_dump -i p0_01.j2k

about:
    home: https://www.openjpeg.org/
    dev_url: https://github.com/uclouvain/openjpeg
    doc_url: https://github.com/uclouvain/openjpeg/wiki/DocJ2KCodec
    license: BSD-2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: An open-source JPEG 2000 codec written in C.
    description: |
      OpenJPEG is an open-source JPEG 2000 codec written in C language.
      It has been developed in order to promote the use of JPEG 2000,
      a still-image compression standard from the Joint Photographic Experts Group (JPEG).
      Since may 2015, it is officially recognized by ISO/IEC and ITU-T
      as a JPEG 2000 Reference Software.

extra:
  recipe-maintainers:
    - gillins
    - mingwandroid
    - ocefpaf
