{% set version = "2.5.3" %}

package:
  name: openjpeg
  version: {{ version }}

source:
  url: https://github.com/uclouvain/openjpeg/archive/v{{ version }}.tar.gz
  sha256: 368fe0468228e767433c9ebdea82ad9d801a3ad1e4234421f352c8b06e7aa707

build:
  number: 0
  run_exports:
    # good compatibility in 2.x series, check before new release
    # http://www.openjpeg.org/abi-check/timeline/openjpeg/
    - {{ pin_subpackage('openjpeg') }}

requirements:
  build:
    - cmake <4
    - make  # [not win]
    - ninja  # [win]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - libtiff
    - libpng
    - zlib

test:
  files:
    - p0_01.j2k
  commands:
    - opj_dump -i p0_01.j2k

about:
  home: http://www.openjpeg.org/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: An open-source JPEG 2000 codec written in C

extra:
  recipe-maintainers:
    - gillins
    - mingwandroid
    - ocefpaf
