# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: generic

os: osx

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "GNN9C8uKN4npBx96azHI0dKLn8a6vmbNS8t1OWZX6F7R38cJ4v3ePjFoALz779HH0C3cedEv377PuoNMS5s9VsYkbe6mVUer3g/rzD90Zw9s9ttX7O1MO1FIWrGNII6AmOiCSg4PMCxcHalaZrNY5rROWLaqiyCFv5FDfmHJ3bUYKKMz67p9/BoJppznPyOhlmUsMItyzeqBHYa4ISN+H8JR9ecj+C1mpPRr6dTaE8OvPFvvLs+8M3yvXZbuPFHXAzRk6Tendhh1wuBp0Z7drYo1ig80SwDbnl2lbTYvCUmtEoHl8skG6NbwSrZgZ/7LA3TxiwcrXabFM5CQxWvgaHfcUMo41XMz9Lq64Ly2b0hnqyZPGdwnRGLtgn3pNuhwuuyvbBa7B86dTlP76uBjcTk1nEFfrgN0s2Rh9GBIA03rrGyHlPE96FnTM4L7AWYbyeMFL+LlnprehcyhGDjqF3h8ldPjEsM0JEn8mJfbaJ0X8WlBuc6yBTxN1DLjaiqIcR/+7ptJHycpDBQGqSkkwRty17+1gRsRFD2mBlBq4QFqARvmcjAVoWqTdAp5jv/zTIM+GYca2yyO5DIndx1fxuA42M1jdJuvVQmXqbmC9WAupYNzTrVg4lwocwjakJGS8SwMbusQGGfxOEGWQMU6wFpymOkhyC29Qi75/W+XBV4="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
