appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: ZcrkgXui57fHh9EWgo7fyFeYQTVgCFc/AQNHhmbp3qC/EcvQ2ys3OWlhEEbnqai4rT4XCnOb/G7RyVkkYA2TgaQyAb9nOlm2krzCZ9uj84NXU9qBIjt1rsYA87SL0zutFhFUr5fRYKyV6nLGA/aWuVbn5iRuszZZyatpPliWdgkxqX5bLOS6QupL0HKzMEcGtsVkuCAXp22ZMtE7raT6UhBmCFTOxuP965peVv1UBHAGkOXdudWoO++dONaaHwcaaLa7Kf7n15tAyt4lA6e0bM+kJ+YTOBLEbKEiXYTiO5Bxzk1oq7S+jtPf0yEx4sKn/wklAbmlZW9uZpgbIMOmbtF7Gto/hSkqQGXc+HaMZqPyTKzfI9Q47AjhDur9T5kKzLYfCHqpg4fDutBq0XtyKyGtyl6e8AnIRNzo5Dt+Z3Fs9KrVgFnl2UoBEKZWZJi6rIF2oGgzzmzJzbZ8ev5faPaUDyCRT3ul0in5Wc9qOMO133AeQoaSopz0Cl5pQbwlPaWj3xFkIBUI9UAFoTsaqgOye+tqa0Ym+K/CaNGEnPACMvjXi+K2Ii+FblolktShYOIY/J+swpRmeZhgohtmrirbePJeQzGAOlpoyZLMXrCEk5vjV33ZehP1PYMOVsg1yEL45dXL9Y3j/qIIkdp4Dav2EbSL185hME19h+lrHec=}
